FROM node:24-alpine AS deps

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY --parents ./packages/*/package.json ./demo-platformer/*/package.json ./

RUN pnpm install --frozen-lockfile

FROM node:24-alpine AS deploy

WORKDIR /app

COPY --exclude=scripts . .
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=deps --parents /app/packages/*/node_modules /app/demo-platformer/*/node_modules /app/../

RUN corepack enable && npm run prebuild

CMD ["pnpm", "e2e:test"]
